### ISSUE TITLE
SE2数据集预处理问题

### ISSUE THREAD

**Issue by neo-dqy** [geekjuruo/GAPA#1]
您好，SE2数据集的语料库和Wiki以及apr有很大的不同，请问能否提供一下预处理SE2的py文件

**Comment by geekjuruo** [comment]
您好，抱歉前一段时间太忙了没来得及回复。关于SE2数据集，我们团队的同学刚刚处理过，你可以联系他获得预处理的文件。马仕镕 Email: masr21@mails.tsinghua.edu.cn (C.C. liyinghu20@mails.tsinghua.edu.cn)
